# Generated by Django 4.2.6 on 2023-10-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('profile_picture', models.ImageField(upload_to='dp/')),
                ('password', models.CharField(max_length=32)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
