# Generated by Django 4.2.6 on 2023-10-28 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manga.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('cover', models.ImageField(upload_to=manga.models.get_filename)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(max_length=200)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
